// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ChatContainer: typeof import('./components/ChatContainer.vue')['default']
    ChatContent: typeof import('./components/ChatContent.vue')['default']
    ChatDomain: typeof import('./components/ChatDomain.vue')['default']
    ChatEditor: typeof import('./components/ChatEditor.vue')['default']
    ChatFoot: typeof import('./components/ChatFoot.vue')['default']
    ChatHead: typeof import('./components/ChatHead.vue')['default']
    ChatNav: typeof import('./components/ChatNav.vue')['default']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    Header: typeof import('./layouts/Header.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}

export {}
